<a href="https://colab.research.google.com/github/Sharonkimani/Email-spam-classification-task/blob/main/classification_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split , cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier



In [2]:
data= pd.read_csv('/content/emails.csv')
data.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [3]:
data.info(memory_usage='deep')
data.drop('Email No.', axis=1, inplace=True)
print(data.info(memory_usage='deep'))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.7 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3001 entries, the to Prediction
dtypes: int64(3001)
memory usage: 118.4 MB
None


In [5]:
print(f'The dataset has {data.duplicated().sum()} duplicates')
print(f'The dataset has {data.isna().sum().sum()} missing values')

The dataset has 541 duplicates
The dataset has 0 missing values


In [10]:
data[data.duplicated(keep=False)]

the  to  ect  and  for  of   a  you  hou  in  ...  connevey  jay  \
2       0   0    1    0    0   0   8    0    0   4  ...         0    0   
204     0   0    1    0    1   0   5    0    0   1  ...         0    0   
252     0   0    1    0    1   0   5    0    0   1  ...         0    0   
302     0   0    1    0    0   0   0    0    0   0  ...         0    0   
444     0   0    1    0    0   0   0    0    0   0  ...         0    0   
...   ...  ..  ...  ...  ...  ..  ..  ...  ...  ..  ...       ...  ...   
4823    0   0    1    1    0   0   7    4    0   4  ...         0    0   
4877    0   0    1    0    0   0   0    0    0   0  ...         0    0   
4943    7   4    3    3    1   4  31    2    1   4  ...         0    0   
5065    0   1    1    1    0   0   8    1    0   4  ...         0    0   
5089    0   1    1    1    0   0   8    1    0   4  ...         0    0   

      valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
2          0    0               0         0         0   0    0           0  
204        0    0               0         0         0   0    0           0  
252        0    0               0         0         0   0    0           0  
302        0    0               0         0         0   0    0           1  
444        0    0               0         0         0   0    0           1  
...      ...  ...             ...       ...       ...  ..  ...         ...  
4823       0    0               0         0         0   0    0           1  
4877       0    0               0         0         0   0    0           1  
4943       0    0               0         0         0   1    0           1  
5065       0    1               0         0         0   0    0           1  
5089       0    1               0         0         0   0    0           1  

[827 rows x 3001 columns]

In [13]:
data.drop_duplicates(inplace=True)
data.duplicated().sum()
data.shape

(4631, 3001)

# Modelling


In [18]:
y =data[['Prediction']]
X= data.drop('Prediction', axis=1)
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.3, random_state=24)

In [19]:
# standardizing
scaler= StandardScaler()
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled= scaler.transform(X_test)

In [20]:
y_train.shape

(3241, 1)

In [21]:
# baseline model
model1= LogisticRegression()
model1.fit(X_train_scaled, y_train)
model1_pred= model1.predict(X_test_scaled)
# Evaluate Logistic Regression
print("Logistic Regression Accuracy:", accuracy_score(y_test, model1_pred))
print("Logistic Regression Classification Report:\n", classification_report(y_test, model1_pred))
print("Logistic Regression Confusion Matrix:\n", confusion_matrix(y_test, model1_pred))


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Logistic Regression Accuracy: 0.962589928057554
Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97       941
           1       0.94      0.94      0.94       449

    accuracy                           0.96      1390
   macro avg       0.96      0.96      0.96      1390
weighted avg       0.96      0.96      0.96      1390

Logistic Regression Confusion Matrix:
 [[916  25]
 [ 27 422]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [22]:
# decision tree classifier
model2= DecisionTreeClassifier()
model2.fit(X_train_scaled, y_train)
model2_pred= model2.predict(X_test_scaled)
# Evaluate the decision tree classifier
print("Decision Tree Classifier Accuracy:", accuracy_score(y_test, model2_pred))
print("Decision Tree Classifier Classification Report:\n", classification_report(y_test, model2_pred))
print("Decision Tree Classifier Confusion Matrix:\n", confusion_matrix(y_test, model2_pred))

Decision Tree Classifier Accuracy: 0.9071942446043165
Decision Tree Classifier Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.94      0.93       941
           1       0.87      0.84      0.85       449

    accuracy                           0.91      1390
   macro avg       0.90      0.89      0.89      1390
weighted avg       0.91      0.91      0.91      1390

Decision Tree Classifier Confusion Matrix:
 [[882  59]
 [ 70 379]]


In [23]:
#Random forest classifer
model3= RandomForestClassifier()
model3.fit(X_train_scaled, y_train)
model3_pred= model3.predict(X_test_scaled)
# Evaluate the random forest classifier
print("Random forest Classifier Accuracy:", accuracy_score(y_test, model3_pred))
print("Random forest Classifier Classification Report:\n", classification_report(y_test, model3_pred))
print("Random forest Classifier Confusion Matrix:\n", confusion_matrix(y_test, model3_pred))

<ipython-input-23-1b02063b5d25>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model3.fit(X_train_scaled, y_train)


Random forest Classifier Accuracy: 0.9712230215827338
Random forest Classifier Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.99      0.98       941
           1       0.97      0.94      0.95       449

    accuracy                           0.97      1390
   macro avg       0.97      0.96      0.97      1390
weighted avg       0.97      0.97      0.97      1390

Random forest Classifier Confusion Matrix:
 [[927  14]
 [ 26 423]]


The best performing model is the random forest classifier. thus that is our chosen model.

In [ ]:

# Define the parameter grid to search
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Create the Random Forest model
rf_model = RandomForestClassifier()

# Instantiate GridSearchCV
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid,
                           cv=3, scoring='accuracy')

# Fit the model to the data
grid_search.fit(X_train_scaled, y_train)

# Get the best parameters from the grid search
best_params = grid_search.best_params_
print("Best Parameters:", best_params)

# Use the best model for predictions
best_rf_model = grid_search.best_estimator_
y_pred_rf_tuned = best_rf_model.predict(X_test_scaled)

# Evaluate the tuned Random Forest Classifier
print("Tuned Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf_tuned))
print("Tuned Random Forest Classification Report:\n", classification_report(y_test, y_pred_rf_tuned))
print("Tuned Random Forest Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf_tuned))


After hyperparameter tuning, the accuracy reduced , using the baseline random forest classifier is the best way to go.